#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=32gb,walltime=0:30:00
#PBS -N prosm-roi-generation
#PBS -V

# generate surfaces and label volume
if [ ! -f R.ProS.msm.label.nii.gz ]; then
	echo $FREESURFER_LICENSE > license.txt
	time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.4.2-freesurfer-update ./run.sh
fi

# genereate prostriata roi
if [ ! -f "R.ProS_vol_1.25.nii.gz" ]; then
	time singularity exec -e docker://brainlife/afni:16.3.0 ./allineate.sh
fi

# threshold prostriata rois & generate LGN
if [ ! -d ./rois ]; then
	time singularity exec -e docker://brainlife/fsl:5.0.9 ./threshold.sh
fi

#if [ -z "rois" ]; then
#	echo "failed"
#	exit 1
#else
#	echo "complete"
#	rm -rf *.gii *.nii.gz freesurfer license.txt label
#	exit 0
#fi
